

CREATE TABLE IF NOT EXISTS `USERS`(
    `ID`          VARCHAR(20),
    `PASSWORD`    VARCHAR(255) NOT NULL,
    `NAME`        VARCHAR(20) NOT NULL,
    PRIMARY KEY(`ID`)
);

CREATE TABLE IF NOT EXISTS `PROFILES`(
    `ID`              INT AUTO_INCREMENT,
    `USER_ID`         VARCHAR(20) NOT NULL,
    `IMAGE`           VARCHAR(255),
    `INSTRODUCTION`   VARCHAR(255),
    `EDU_NAME`        VARCHAR(255),
    `MAJOR`           VARCHAR(100),
    `EDU_STATUS`      VARCHAR(10),
    PRIMARY KEY(`ID`),
    FOREIGN KEY(USER_ID) REFERENCES USERS(`ID`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `AWARDS`(
    `ID`          INT AUTO_INCREMENT,
    `USER_ID`     VARCHAR(20) NOT NULL,
    `AWARD`       VARCHAR(255),
    `DETAILS`     TEXT,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`USER_ID`) REFERENCES USERS(`ID`) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `PORTFOLIOS`(
    `ID`          INT AUTO_INCREMENT,
    `USER_ID`     VARCHAR(20) NOT NULL,
    `TITLE`       VARCHAR(255),
    `CONTENT`     TEXT,
    `START_DATE`  DATE,
    `END_DATE`    DATE,
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`USER_ID`) REFERENCES USERS(`ID`) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `CERTIFICATES`(
    `ID`          INT AUTO_INCREMENT,
    `USER_ID`     VARCHAR(20) NOT NULL,
    `NAME`        VARCHAR(255),
    `ISSUED_BY`   VARCHAR(255),
    PRIMARY KEY(`ID`),
    FOREIGN KEY(`USER_ID`) REFERENCES USERS(`ID`) ON DELETE CASCADE
);